-- ----------------------------
-- 1. Limpieza Inicial
-- ----------------------------

-- Limpiamos las tablas en orden, usando CASCADE para resolver dependencias.
DROP VIEW IF EXISTS public.dashboard_stats;
DROP VIEW IF EXISTS public.agreements_with_counts;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.agreement_promotions CASCADE;
DROP TABLE IF EXISTS public.agreement_sales_conditions CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.agreements CASCADE;
DROP TABLE IF EXISTS public.price_list_items CASCADE;
DROP TABLE IF EXISTS public.price_lists CASCADE;
DROP TABLE IF EXISTS public.promotions CASCADE;
DROP TABLE IF EXISTS public.sales_conditions CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;

-- Limpiamos las funciones de forma explícita especificando sus argumentos para evitar errores de ambigüedad.
DROP FUNCTION IF EXISTS public.increment_total_revenue(real);
DROP FUNCTION IF EXISTS public.get_client_stats(uuid);
DROP FUNCTION IF EXISTS public.update_dashboard_stats();


-- ----------------------------
-- 2. Creación de Tablas
-- ----------------------------

-- Tabla de Productos
CREATE TABLE public.products (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL,
    description text,
    category text,
    image_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Tabla de Listas de Precios
CREATE TABLE public.price_lists (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    prices_include_vat boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Tabla de Items de Listas de Precios (tabla pivote)
CREATE TABLE public.price_list_items (
    price_list_id uuid NOT NULL REFERENCES public.price_lists(id) ON DELETE CASCADE,
    product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    price real NOT NULL,
    volume_price real,
    PRIMARY KEY (price_list_id, product_id)
);

-- Tabla de Promociones
CREATE TABLE public.promotions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    rules jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Tabla de Condiciones de Venta
CREATE TABLE public.sales_conditions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    rules jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Tabla de Convenios
CREATE TABLE public.agreements (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    agreement_name text NOT NULL UNIQUE,
    client_type public.client_type_enum NOT NULL,
    price_list_id uuid REFERENCES public.price_lists(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Tabla de Clientes
CREATE TABLE public.clients (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    cuit text UNIQUE,
    contact_name text,
    contact_dni text,
    address text,
    delivery_window text,
    email text UNIQUE,
    instagram text,
    status public.client_status_enum DEFAULT 'pending_onboarding'::public.client_status_enum NOT NULL,
    onboarding_token uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    agreement_id uuid REFERENCES public.agreements(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    fiscal_status text
);

-- Tabla de Pedidos
CREATE TABLE public.orders (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE RESTRICT,
    agreement_id uuid NOT NULL REFERENCES public.agreements(id) ON DELETE RESTRICT,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    total_amount real NOT NULL,
    status public.order_status_enum DEFAULT 'pending'::public.order_status_enum NOT NULL,
    client_name_cache text NOT NULL
);

-- Tabla de Items de Pedidos
CREATE TABLE public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    quantity integer NOT NULL,
    price_per_unit real NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Tabla pivote para Convenios y Promociones
CREATE TABLE public.agreement_promotions (
    agreement_id uuid NOT NULL REFERENCES public.agreements(id) ON DELETE CASCADE,
    promotion_id uuid NOT NULL REFERENCES public.promotions(id) ON DELETE CASCADE,
    PRIMARY KEY (agreement_id, promotion_id)
);

-- Tabla pivote para Convenios y Condiciones de Venta
CREATE TABLE public.agreement_sales_conditions (
    agreement_id uuid NOT NULL REFERENCES public.agreements(id) ON DELETE CASCADE,
    sales_condition_id uuid NOT NULL REFERENCES public.sales_conditions(id) ON DELETE CASCADE,
    PRIMARY KEY (agreement_id, sales_condition_id)
);


-- ----------------------------
-- 3. Vistas
-- ----------------------------

-- Vista para obtener convenios con conteo de promociones y condiciones
CREATE VIEW public.agreements_with_counts AS
SELECT 
    a.id,
    a.agreement_name,
    a.client_type,
    a.created_at,
    a.price_list_id,
    (SELECT COUNT(*) FROM public.agreement_promotions ap WHERE ap.agreement_id = a.id) as promotion_count,
    (SELECT COUNT(*) FROM public.agreement_sales_conditions sc WHERE sc.agreement_id = a.id) as sales_condition_count
FROM 
    public.agreements a;


-- Vista para estadísticas del dashboard (simplificada)
CREATE VIEW public.dashboard_stats AS
SELECT
    (SELECT COALESCE(sum(total_amount), 0) FROM public.orders WHERE status = 'completed') AS total_revenue,
    (SELECT COALESCE(sum(total_amount), 0) FROM public.orders WHERE status = 'completed' AND created_at >= date_trunc('month', now())) AS month_revenue,
    (SELECT COUNT(*) FROM public.clients WHERE status = 'active') AS active_clients;


-- ----------------------------
-- 4. Funciones RPC (Remote Procedure Call)
-- ----------------------------

-- Función para incrementar los ingresos totales. Más segura que un UPDATE directo desde el frontend.
CREATE OR REPLACE FUNCTION public.increment_total_revenue(amount_to_add real)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    -- This function is a placeholder for a more robust revenue tracking system.
    -- In a real-world scenario, this might involve updating an aggregate table
    -- or logging transactions in a way that avoids direct updates to a single row
    -- from multiple clients, which can cause lock contention.
    -- For this demo, we are simply showing the concept.
    -- The dashboard_stats view will reflect the changes in the orders table.
END;
$$;

-- Función para obtener estadísticas de un cliente específico.
CREATE OR REPLACE FUNCTION public.get_client_stats(p_client_id uuid)
RETURNS TABLE(total_spent real, average_order_value real, total_orders bigint)
LANGUAGE sql
AS $$
    SELECT
        COALESCE(SUM(total_amount), 0.0)::real AS total_spent,
        COALESCE(AVG(total_amount), 0.0)::real AS average_order_value,
        COUNT(id) AS total_orders
    FROM
        public.orders
    WHERE
        client_id = p_client_id;
$$;


-- ----------------------------
-- 5. Políticas de Seguridad (RLS)
-- ----------------------------

-- Habilitar RLS en todas las tablas
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agreement_promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agreement_sales_conditions ENABLE ROW LEVEL SECURITY;

-- Creamos una política genérica para permitir el acceso total a los usuarios autenticados.
-- Esto es seguro en este contexto porque la app solo permite el login a administradores.
-- En una app con diferentes roles de usuario, se necesitarían políticas más granulares.

CREATE POLICY "Allow all access to authenticated users" ON public.products
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow all access to authenticated users" ON public.price_lists
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow all access to authenticated users" ON public.price_list_items
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow all access to authenticated users" ON public.promotions
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow all access to authenticated users" ON public.sales_conditions
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow all access to authenticated users" ON public.agreements
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow read access to everyone" ON public.clients
    FOR SELECT USING (true);
CREATE POLICY "Allow full access to authenticated users" ON public.clients
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow all access to authenticated users" ON public.orders
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow insert by anyone" ON public.orders
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow all access to authenticated users" ON public.order_items
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow insert by anyone" ON public.order_items
    FOR INSERT WITH CHECK (true);
    
CREATE POLICY "Allow all access to authenticated users" ON public.agreement_promotions
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow all access to authenticated users" ON public.agreement_sales_conditions
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow read access to everyone" ON public.agreements
    FOR SELECT USING (true);
    
CREATE POLICY "Allow read access to everyone" ON public.price_lists
    FOR SELECT USING (true);
    
CREATE POLICY "Allow read access to everyone" ON public.price_list_items
    FOR SELECT USING (true);

CREATE POLICY "Allow read access to everyone" ON public.products
    FOR SELECT USING (true);

CREATE POLICY "Allow read access to everyone" ON public.promotions
    FOR SELECT USING (true);
    
CREATE POLICY "Allow read access to everyone" ON public.agreement_promotions
    FOR SELECT USING (true);


-- ----------------------------
-- 6. Storage
-- ----------------------------
-- Creamos el bucket para las imágenes de productos si no existe.
INSERT INTO storage.buckets (id, name, public)
VALUES ('product_images', 'product_images', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de seguridad para el bucket de imágenes.
-- Permite que cualquiera pueda ver las imágenes (SELECT)
CREATE POLICY "Public read access for product images"
ON storage.objects FOR SELECT
USING ( bucket_id = 'product_images' );

-- Permite que los usuarios autenticados (admins) puedan subir, actualizar y borrar imágenes.
CREATE POLICY "Allow insert for authenticated users"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'product_images' );

CREATE POLICY "Allow update for authenticated users"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'product_images' );

CREATE POLICY "Allow delete for authenticated users"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'product_images' );
