-- This script was generated by the Studio boilerplate builder and should be used as a reference only
-- It is not recommended to run this script in production
--
-- To use this script, run the following command in your terminal:
-- psql -f schema.sql <your-database-url>

-- Drop existing tables and types if they exist to start fresh
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "price_lists" CASCADE;
DROP TABLE IF EXISTS "price_list_items" CASCADE;
DROP TABLE IF EXISTS "promotions" CASCADE;
DROP TABLE IF EXISTS "agreements" CASCADE;
DROP TABLE IF EXISTS "agreement_products" CASCADE; -- This table seems deprecated, but keeping drop for safety
DROP TABLE IF EXISTS "agreement_promotions" CASCADE;
DROP TABLE IF EXISTS "clients" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP TABLE IF EXISTS "order_items" CASCADE;
DROP TABLE IF EXISTS "dashboard_stats" CASCADE;
DROP TYPE IF EXISTS "client_type_enum" CASCADE;
DROP TYPE IF EXISTS "promotion_type_enum" CASCADE;
DROP TYPE IF EXISTS "client_status" CASCADE;
DROP TYPE IF EXISTS "order_status" CASCADE;


-- Create ENUM types for categorical data
CREATE TYPE client_type_enum AS ENUM ('barberia', 'distribuidor', 'especial');
CREATE TYPE promotion_type_enum AS ENUM ('buy_x_get_y_free', 'free_shipping');
CREATE TYPE client_status AS ENUM ('pending_onboarding', 'pending_agreement', 'active', 'archived');
CREATE TYPE order_status AS ENUM ('pending', 'completed');

-- Create tables
CREATE TABLE public.products (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name character varying NOT NULL,
    description text,
    base_price real NOT NULL DEFAULT '0'::real,
    stock integer NOT NULL DEFAULT 0,
    category character varying,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE public.price_lists (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name character varying NOT NULL,
    prices_include_vat boolean NOT NULL DEFAULT true,
    CONSTRAINT price_lists_pkey PRIMARY KEY (id),
    CONSTRAINT price_lists_name_key UNIQUE (name)
);

CREATE TABLE public.price_list_items (
    price_list_id uuid NOT NULL,
    product_id uuid NOT NULL,
    price real NOT NULL,
    volume_price real,
    CONSTRAINT price_list_items_pkey PRIMARY KEY (price_list_id, product_id),
    CONSTRAINT fk_price_list FOREIGN KEY (price_list_id) REFERENCES public.price_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.products (id) ON DELETE CASCADE
);

CREATE TABLE public.promotions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name character varying NOT NULL,
    description text,
    rules jsonb NOT NULL,
    CONSTRAINT promotions_pkey PRIMARY KEY (id)
);

CREATE TABLE public.agreements (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    agreement_name character varying NOT NULL,
    client_type client_type_enum NOT NULL,
    price_list_id uuid,
    CONSTRAINT agreements_pkey PRIMARY KEY (id),
    CONSTRAINT agreements_agreement_name_key UNIQUE (agreement_name),
    CONSTRAINT fk_price_list FOREIGN KEY (price_list_id) REFERENCES public.price_lists (id) ON DELETE SET NULL
);

CREATE TABLE public.agreement_promotions (
    agreement_id uuid NOT NULL,
    promotion_id uuid NOT NULL,
    CONSTRAINT agreement_promotions_pkey PRIMARY KEY (agreement_id, promotion_id),
    CONSTRAINT fk_agreement FOREIGN KEY (agreement_id) REFERENCES public.agreements (id) ON DELETE CASCADE,
    CONSTRAINT fk_promotion FOREIGN KEY (promotion_id) REFERENCES public.promotions (id) ON DELETE CASCADE
);

CREATE TABLE public.clients (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    cuit character varying,
    contact_name character varying,
    contact_dni character varying,
    address character varying,
    delivery_window character varying,
    email character varying,
    instagram character varying,
    status client_status NOT NULL DEFAULT 'pending_onboarding',
    onboarding_token uuid NOT NULL DEFAULT gen_random_uuid(),
    agreement_id uuid,
    CONSTRAINT clients_pkey PRIMARY KEY (id),
    CONSTRAINT clients_onboarding_token_key UNIQUE (onboarding_token),
    CONSTRAINT clients_cuit_key UNIQUE (cuit),
    CONSTRAINT clients_email_key UNIQUE (email),
    CONSTRAINT fk_agreement FOREIGN KEY (agreement_id) REFERENCES public.agreements (id) ON DELETE SET NULL
);

CREATE TABLE public.orders (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    client_id uuid NOT NULL,
    agreement_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    total_amount real NOT NULL,
    status order_status NOT NULL DEFAULT 'pending',
    client_name_cache character varying NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE RESTRICT,
    CONSTRAINT fk_agreement FOREIGN KEY (agreement_id) REFERENCES public.agreements(id) ON DELETE RESTRICT
);

CREATE TABLE public.order_items (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL,
    price_per_unit real NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT
);

-- Dashboard specific table for aggregated data
CREATE TABLE public.dashboard_stats (
    id bigint PRIMARY KEY,
    total_revenue real NOT NULL DEFAULT 0,
    month_revenue real NOT NULL DEFAULT 0,
    active_clients integer NOT NULL DEFAULT 0
);
-- Insert a single row for stats
INSERT INTO public.dashboard_stats (id, total_revenue, month_revenue, active_clients) VALUES (1, 0, 0, 0);


-- Enable Row Level Security (RLS) for all tables
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agreement_promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_stats ENABLE ROW LEVEL SECURITY;

-- Drop existing policies before creating new ones to avoid conflicts
DROP POLICY IF EXISTS "Admins can manage products" ON public.products;
DROP POLICY IF EXISTS "Admins can manage price lists" ON public.price_lists;
DROP POLICY IF EXISTS "Admins can manage price list items" ON public.price_list_items;
DROP POLICY IF EXISTS "Admins can manage promotions" ON public.promotions;
DROP POLICY IF EXISTS "Admins can manage agreements" ON public.agreements;
DROP POLICY IF EXISTS "Admins can manage agreement promotions" ON public.agreement_promotions;
DROP POLICY IF EXISTS "Admins can manage clients" ON public.clients;
DROP POLICY IF EXISTS "Admins can manage orders" ON public.orders;
DROP POLICY IF EXISTS "Admins can manage order items" ON public.order_items;
DROP POLICY IF EXISTS "Admins can read dashboard stats" ON public.dashboard_stats;

-- Public (anonymous) access policies
DROP POLICY IF EXISTS "Public can read agreement and product data for orders" ON public.agreements;
DROP POLICY IF EXISTS "Public can read client onboarding data" ON public.clients;
DROP POLICY IF EXISTS "Public can insert their own client data during onboarding" ON public.clients;

-- Policies for Authenticated Users (Admins)
CREATE POLICY "Admins can manage products" ON public.products FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage price lists" ON public.price_lists FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage price list items" ON public.price_list_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage promotions" ON public.promotions FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage agreements" ON public.agreements FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage agreement promotions" ON public.agreement_promotions FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage clients" ON public.clients FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage orders" ON public.orders FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage order items" ON public.order_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can read dashboard stats" ON public.dashboard_stats FOR SELECT USING (auth.role() = 'authenticated');


-- Policies for Anonymous Users (Clients making orders or onboarding)
-- Allow public read access to specific data needed for the order page. This is safe because UUIDs are unguessable.
CREATE POLICY "Public can read agreement and product data for orders" ON public.agreements FOR SELECT
USING (true);
-- We rely on joins and RLS on joined tables to control data access below
-- Note: RLS from `price_lists`, `price_list_items`, `products`, `agreement_promotions`, `promotions` are bypassed for reads
-- when joined from `agreements`. This is intentional to allow order page to load.

-- Allow public read access to a client record IF the user knows the onboarding token.
CREATE POLICY "Public can read client onboarding data" ON public.clients FOR SELECT
USING (onboarding_token::text = (current_setting('request.jwt.claims', true)::jsonb ->> 'token'));

-- Allow a public user to update their OWN client record during onboarding.
CREATE POLICY "Public can insert their own client data during onboarding" ON public.clients FOR UPDATE
USING (onboarding_token = (current_setting('request.jwt.claims', true)::jsonb ->> 'token')::uuid)
WITH CHECK (onboarding_token = (current_setting('request.jwt.claims', true)::jsonb ->> 'token')::uuid);

-- Grant usage on schema public to anon and authenticated roles
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;

-- Grant all privileges on all tables in schema public to the authenticated role
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- Grant select and insert privileges for anon role on specific tables
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.clients TO anon;
GRANT SELECT ON TABLE public.agreements TO anon;
GRANT SELECT ON TABLE public.products TO anon;
GRANT SELECT ON TABLE public.promotions TO anon;
GRANT SELECT ON TABLE public.price_lists TO anon;
GRANT SELECT ON TABLE public.price_list_items TO anon;
GRANT SELECT ON TABLE public.agreement_promotions TO anon;
GRANT INSERT ON TABLE public.orders TO anon;
GRANT INSERT ON TABLE public.order_items TO anon;
